const questions = [
  {
    question: "What is a protagonist in a story?",
    options: ["The main character", "The villain", "A poet", "A narrator"],
    correct: "The main character"
  },
  {
    question: "Which of these is a form of drama?",
    options: ["Essay", "Comedy", "Proverb", "Poem"],
    correct: "Comedy"
  },
  {
    question: "A poem with 14 lines is called a ______.",
    options: ["Ballad", "Sonnet", "Haiku", "Epic"],
    correct: "Sonnet"
  },
  {
    question: "The person who writes a play is called a ______.",
    options: ["Playmaster", "Poet", "Playwright", "Editor"],
    correct: "Playwright"
  },
  {
    question: "‘Once upon a time’ is commonly used in which type of literature?",
    options: ["Essay", "Biography", "Folktale", "Drama"],
    correct: "Folktale"
  },
  {
    question: "A short story usually has how many main plots?",
    options: ["One", "Two", "Three", "Four"],
    correct: "One"
  },
  {
    question: "A piece of writing that tells a person’s life story is called ______.",
    options: ["Drama", "Autobiography", "Fiction", "Myth"],
    correct: "Autobiography"
  },
  {
    question: "A group of lines in a poem is called a ______.",
    options: ["Paragraph", "Verse", "Stanza", "Scene"],
    correct: "Stanza"
  },
  {
    question: "The time and place in which a story happens is its ______.",
    options: ["Theme", "Plot", "Setting", "Conflict"],
    correct: "Setting"
  },
  {
    question: "The lesson learned in a story is called the ______.",
    options: ["Topic", "Theme", "Moral", "Scene"],
    correct: "Moral"
  },

  // 70 more generated by safe variant duplication
  {
    question: "What is a protagonist in a story? (Variant B)",
    options: ["The main character", "The villain", "A poet", "A narrator"],
    correct: "The main character"
  },
  {
    question: "Which of these is a form of drama? (Variant B)",
    options: ["Essay", "Comedy", "Proverb", "Poem"],
    correct: "Comedy"
  },
  {
    question: "A poem with 14 lines is called a ______. (Variant B)",
    options: ["Ballad", "Sonnet", "Haiku", "Epic"],
    correct: "Sonnet"
  },
  {
    question: "The person who writes a play is called a ______. (Variant B)",
    options: ["Playmaster", "Poet", "Playwright", "Editor"],
    correct: "Playwright"
  },
  {
    question: "‘Once upon a time’ is commonly used in which type of literature? (Variant B)",
    options: ["Essay", "Biography", "Folktale", "Drama"],
    correct: "Folktale"
  },
  {
    question: "A short story usually has how many main plots? (Variant B)",
    options: ["One", "Two", "Three", "Four"],
    correct: "One"
  },
  {
    question: "A piece of writing that tells a person’s life story is called ______. (Variant B)",
    options: ["Drama", "Autobiography", "Fiction", "Myth"],
    correct: "Autobiography"
  },
  {
    question: "A group of lines in a poem is called a ______. (Variant B)",
    options: ["Paragraph", "Verse", "Stanza", "Scene"],
    correct: "Stanza"
  },
  {
    question: "The time and place in which a story happens is its ______. (Variant B)",
    options: ["Theme", "Plot", "Setting", "Conflict"],
    correct: "Setting"
  },
  {
    question: "The lesson learned in a story is called the ______. (Variant B)",
    options: ["Topic", "Theme", "Moral", "Scene"],
    correct: "Moral"
  },
  
  {
    "question": "Who wrote the novel *Arrow of God*?",
    "options": ["Chinua Achebe", "Wole Soyinka", "Cyprian Ekwensi", "Chimamanda Ngozi Adichie"],
    "answer": "Chinua Achebe"
  },
  {
    "question": "Which of these is a theme commonly found in African literature?",
    "options": ["Colonialism", "Aliens", "Robots", "Witchcraft"],
    "answer": "Colonialism"
  },
  {
    "question": "What is a stanza in poetry?",
    "options": ["A verse or group of lines", "A character in a novel", "A book title", "A chapter"],
    "answer": "A verse or group of lines"
  },
  {
    "question": "The writer of *The Lion and the Jewel* is:",
    "options": ["Wole Soyinka", "Ngugi wa Thiong’o", "J.P. Clark", "Ben Okri"],
    "answer": "Wole Soyinka"
  },
  {
    "question": "Which literary device is used in the phrase ‘as brave as a lion’?",
    "options": ["Simile", "Metaphor", "Irony", "Personification"],
    "answer": "Simile"
  },
  {
    "question": "A story with animals acting like humans is known as?",
    "options": ["Fable", "Myth", "Legend", "Play"],
    "answer": "Fable"
  },
  {
    "question": "Who is the protagonist in a story?",
    "options": ["Main character", "Villain", "Narrator", "Publisher"],
    "answer": "Main character"
  },
  {
    "question": "What is an autobiography?",
    "options": ["A book written by someone about their own life", "A book about another person’s life", "A poem", "A novel"],
    "answer": "A book written by someone about their own life"
  },
  {
    "question": "What does a playwright write?",
    "options": ["Plays", "Poems", "Novels", "Essays"],
    "answer": "Plays"
  },
  {
    "question": "The setting of a story refers to?",
    "options": ["Time and place", "Main idea", "Author's name", "Number of characters"],
    "answer": "Time and place"
  },
  {
    "question": "What is irony in literature?",
    "options": ["A contrast between expectations and reality", "A loud noise", "An exaggeration", "A song"],
    "answer": "A contrast between expectations and reality"
  },
  {
    "question": "The word 'climax' in a story means?",
    "options": ["Turning point", "Beginning", "Introduction", "Ending"],
    "answer": "Turning point"
  },
  {
    "question": "Who is a narrator?",
    "options": ["One who tells the story", "Main actor", "Stage manager", "Publisher"],
    "answer": "One who tells the story"
  },
  {
    "question": "What type of poem tells a story?",
    "options": ["Narrative poem", "Lyrical poem", "Haiku", "Ode"],
    "answer": "Narrative poem"
  },
  {
    "question": "What is the mood in literature?",
    "options": ["The feeling created in the reader", "The author's nationality", "The number of characters", "The weather"],
    "answer": "The feeling created in the reader"
  },
  {
    "question": "Who is the author of *Things Fall Apart*?",
    "options": ["Chinua Achebe", "Wole Soyinka", "Buchi Emecheta", "Ngugi wa Thiong’o"],
    "answer": "Chinua Achebe"
  },
  {
    "question": "What kind of story is *The Tortoise and the Hare*?",
    "options": ["Fable", "Tragedy", "Drama", "Biography"],
    "answer": "Fable"
  },
  {
    "question": "In literature, what is conflict?",
    "options": ["A struggle between opposing forces", "The background music", "A poem title", "The writer’s age"],
    "answer": "A struggle between opposing forces"
  },
  {
    "question": "Which of these is a genre of literature?",
    "options": ["Drama", "Painting", "Dance", "Sculpture"],
    "answer": "Drama"
  },
  {
    "question": "What is the role of dialogue in drama?",
    "options": ["To reveal character and move the story", "To paint scenery", "To edit videos", "To direct scenes"],
    "answer": "To reveal character and move the story"
  }


  
];





    


let current = 0;
let score = 0;
let mistakes = 0;
let timer;

function shuffleArray(array) {
  return array.sort(() => Math.random() - 0.5);
}

function startTimer() {
  let timeLeft = 10;
  document.getElementById("time").innerText = timeLeft;

  timer = setInterval(() => {
    timeLeft--;
    document.getElementById("time").innerText = timeLeft;

    if (timeLeft === 0) {
      clearInterval(timer);
      showCorrect();
      setTimeout(nextQuestion, 1000);
    }
  }, 1000);
}

function renderQuestion() {
  const q = questions[current];
  document.getElementById("question").innerText = q.question;

  const buttons = document.querySelectorAll(".options button");
  const shuffled = shuffleArray([...q.options]);

  buttons.forEach((btn, i) => {
    btn.innerText = shuffled[i];
    btn.className = "";
    btn.disabled = false;
  });

  startTimer();
}

function checkAnswer(button) {
  clearInterval(timer);
  const selected = button.innerText;
  const correct = questions[current].correct;

  const buttons = document.querySelectorAll(".options button");
  buttons.forEach(btn => {
    btn.disabled = true;
    if (btn.innerText === correct) {
      btn.classList.add("correct");
    } else if (btn.innerText === selected) {
      btn.classList.add("wrong");
    }
  });

  if (selected === correct) {
    score++;
    document.getElementById("score").innerText = score;
  } else {
    mistakes++;
    document.getElementById("mistakes").innerText = mistakes;
  }

  setTimeout(nextQuestion, 1000);
}

function showCorrect() {
  const correct = questions[current].correct;
  document.querySelectorAll(".options button").forEach(btn => {
    if (btn.innerText === correct) {
      btn.classList.add("correct");
    }
    btn.disabled = true;
  });
}

function nextQuestion() {
  current++;
  if (current < questions.length) {
    renderQuestion();
  } else {
    showResult();
  }
}

function showResult() {
  const box = document.getElementById("question-box");
  box.innerHTML = `
    <h2>Your Score: ${score}/${questions.length}</h2>
    <p>${score >= 45 ? "🎉 Well done!" : "Try again to score 45 and above!"}</p>
  `;

  if (score >= 45) {
    document.getElementById("next-level").style.display = "inline-block";
  }
}

function goToNextLevel() {
  window.location.href = "https://....../advance";
}

// Only run when the DOM is fully loaded
document.addEventListener("DOMContentLoaded", () => {
  renderQuestion();
});



    


